#!/usr/local/bin/perl
#  Copyright 2012, by the California Institute of Technology.  ALL RIGHTS
#  RESERVED. United States Government Sponsorship acknowledged. Any commercial
#  use must be negotiated with the Office of Technology Transfer at the
#  California Institute of Technology.
#
# $Id$
# DO NOT EDIT THE LINE ABOVE - IT IS AUTOMATICALLY GENERATED BY CM

# Program will crawl a given directory and uncompress any .bz2 files it finds.  It will read the "Processing Version" attribute to determine if it is quicklook
# or refined and move the file to the appropriate bucket.  There should be 2 input buckets and 4 output buckets:
#
# Input buckets:
#
#    MODIS_AQUA_L2_SST_OBPG
#    MODIS_TERRA_L2_SST_OBPG
#
# Output buckets:
#
#    MODIS_AQUA_L2_SST_OBPG_QUICKLOOK
#    MODIS_AQUA_L2_SST_OBPG_REFINED
#    MODIS_TERRA_L2_SST_OBPG_QUICKLOOK
#    MODIS_TERRA_L2_SST_OBPG_REFINED
#
# The bucket's name is determined by appending to the variable i_modis_search_directory either "_QUICKLOOK" or "_REFINED".
#
#------------------------------------------------------------------------------------------------

# Location of GHRSST Perl library functions.

$GHRSST_PERL_LIB_DIRECTORY = $ENV{GHRSST_PERL_LIB_DIRECTORY};

do "$GHRSST_PERL_LIB_DIRECTORY/modis_level2_uncompressor_driver.pl";

use File::Basename;
use File::Copy;

my $NUM_FILES_TO_PROCESS = 500;  # Default number of files to process.  Will reset to smaller number if input is smaller.
$g_routine_name = "modis_level2_uncompressor";

#------------------------------------------------------------------------------------------------------------------------
# Begin of main subroutine modis_level2_uncompressor.
#
# A few global variables.

$g_debug = 0;
$g_routine_name = "modis_level2_uncompressor";

my $i_datatype          = "sea_surface_temperature";
my $i_datasource        = "MODIS_A";
my $i_processing_type   = "MODIS_A";
my $i_modis_search_directory = "";
my $i_modis_data_name_prefix = "A";

my $num_args = $#ARGV + 1;

# Do sanity check to make sure we have the correct number of parameters.

if ($num_args < 3 ) {
	print "usage: perl modis_level2_uncompressor.pl datasource search_directory                                   num_files_to_uncompress value_move_instead_of_copy \n";
	print "usage: perl modis_level2_uncompressor.pl MODIS_A    /data/dev/scratch/IO/modis/MODIS_AQUA_L2_SST_OBPG  30 yes\n";
	print "usage: perl modis_level2_uncompressor.pl MODIS_A    /data/dev/scratch/IO/modis/MODIS_AQUA_L2_SST_OBPG  1  no\n";
	print "usage: perl modis_level2_uncompressor.pl MODIS_T    /data/dev/scratch/IO/modis/MODIS_TERRA_L2_SST_OBPG 30 yes\n";
	print "usage: perl modis_level2_uncompressor.pl MODIS_T    /data/dev/scratch/IO/modis/MODIS_TERRA_L2_SST_OBPG 1  no\n";
	print "usage: perl modis_level2_uncompressor.pl VIIRS      /data/dev/scratch/IO/modis/VIIRS_L2_SST_OBPG 1  no\n";
	exit(1);
}

# Get the input parameters.

$i_datasource              = $ARGV[0];
$i_processing_type         = $i_datasource;  # The processing type and source are the same in our case.
$i_modis_search_directory  = $ARGV[1];
$i_num_files_to_uncompress = $ARGV[2];
$i_value_move_instead_of_copy = "";


if ($ARGV[3] ne '') {
    $i_value_move_instead_of_copy = $ARGV[3];
}

# Check to see if we want to debug or not.
if ($ARGV[4] ne '') {
    if ($ARGV[4] eq 'yes') {
        $g_debug = 1;
    }  
}

if ($i_processing_type eq "MODIS_A") {
    $i_modis_data_name_prefix = "A";
} elsif ($i_processing_type eq "MODIS_T") {
    $i_modis_data_name_prefix = "T";
} elsif ($i_processing_type eq "VIIRS") {
    $i_modis_data_name_prefix = "V";
}

if ($ENV{GHRSST_MODIS_L2_UNCOMPRESSOR_DEBUG_MODE} eq "true") {
    $g_debug = 1;
}

# Do the uncompression and exit;

my $uncompressor_driver_status = modis_level2_uncompressor_driver($i_datatype, 
                                                                  $i_datasource, 
                                                                  $i_processing_type, 
                                                                  $i_modis_search_directory, 
                                                                  $i_modis_data_name_prefix, 
                                                                  $i_num_files_to_uncompress, 
                                                                  $i_value_move_instead_of_copy);

exit(0);

# End of of main subroutine modis_level2_uncompressor.
